<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ptz_robot">

  <xacro:property name="base_radius" value="0.12" />
  <xacro:property name="base_height" value="0.08" />

  <xacro:property name="pan_link_length" value="0.4" />
  <xacro:property name="pan_link_radius" value="0.04" />

  <xacro:property name="tilt_box_x" value="0.2" />
  <xacro:property name="tilt_box_y" value="0.13" />
  <xacro:property name="tilt_box_z" value="0.1" />
  <xacro:property name="lens_length" value="0.2" />
  <xacro:property name="lens_radius" value="0.045" />

  <material name="dark_grey">
    <color rgba="0.2 0.2 0.2 1"/>
  </material>
  <material name="brushed_aluminum">
    <color rgba="0.7 0.7 0.75 1"/>
  </material>
  <material name="lens_black">
    <color rgba="0.05 0.05 0.05 1"/>
  </material>
  <material name="sensor_glass">
    <color rgba="0.0 0.5 0.8 0.6"/>
  </material>

  <xacro:macro name="inertial_matrix" params="mass ixx:=0.01 iyy:=0.01 izz:=0.01">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}" />
      <inertia ixx="${ixx}" ixy="0.0" ixz="0.0"
               iyy="${iyy}" iyz="0.0"
               izz="${izz}" />
    </inertial>
  </xacro:macro>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- ==========================
       Base link (flat disk)
       ========================== -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="2.0"/>
  </link>

  <joint name="pan_joint" type="continuous">
    <parent link="base_link"/>
    <child link="pan_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <!-- <limit lower="-3.14" upper="3.14" effort="30" velocity="2.0"/> -->
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- ==========================
       Pan link (vertical cylinder)
       ========================== -->
  <link name="pan_link">
    <visual>
      <origin xyz="0 0 ${pan_link_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${pan_link_length}" radius="${pan_link_radius}"/>
      </geometry>
      <material name="brushed_aluminum"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${pan_link_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${pan_link_length}" radius="${pan_link_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="0.5"/>
  </link>

  <joint name="tilt_joint" type="revolute">
    <parent link="pan_link"/>
    <child link="tilt_link"/>
    <origin xyz="0 0 ${pan_link_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.2" upper="0.5" effort="10" velocity="1.5"/>
    <dynamics damping="0.1" friction="0.5"/>
  </joint>

  <!-- ==========================
       Tilt link (horizontal rod)
       ========================== -->
  <link name="tilt_link">
    <visual>
      <geometry>
        <box size="${tilt_box_x} ${tilt_box_y} ${tilt_box_z}"/>
      </geometry>
      <material name="brushed_aluminum"/>
    </visual>
    <collision>
      <geometry>
        <box size="${tilt_box_x} ${tilt_box_y} ${tilt_box_z}"/>
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="0.5"/>
  </link>

  <joint name="zoom_joint" type="prismatic">
    <parent link="tilt_link"/>
    <child link="camera_lens_link"/>
    <origin xyz="${tilt_box_x/2 + 0.01} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0.0" upper="0.16" effort="300.0" velocity="0.55"/>
    <dynamics damping="0.1"/>
  </joint>

  <!-- ==========================
       Zoom slider (prismatic)
       ========================== -->
  <link name="camera_lens_link">
    <visual>
      <origin xyz="${-lens_length/2 + 0.01} 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="${lens_length}" radius="${lens_radius}"/>
      </geometry>
      <material name="lens_black"/>
    </visual>
    <collision>
       <origin xyz="${-lens_length/2 + 0.01} 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="${lens_length}" radius="${lens_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="0.2"/>
  </link>

  <joint name="camera_tip_joint" type="fixed">
    <parent link="camera_lens_link"/>
    <child link="camera_glass_link"/>
    <origin xyz="0.01 0 0" rpy="0 0 0"/>
  </joint>

  <!-- ==========================
       Camera body
       ========================== -->
       <link name="camera_glass_link">
         <!-- sensor glass -->
         <visual name="glass_disk">
           <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
           <geometry>
             <cylinder length="0.01" radius="${lens_radius - 0.005}"/>
           </geometry>
           <material name="sensor_glass"/>
         </visual>

         <!-- inner “aperture” disk for depth -->
         <visual name="inner_aperture">
           <origin xyz="-0.001 0 0" rpy="0 ${pi/2} 0"/>
           <geometry>
             <cylinder length="0.003" radius="${lens_radius*0.55}"/>
           </geometry>
           <material name="lens_black"/>
         </visual>
       </link>

  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_glass_link"/>
    <child link="camera_link_optical"/>
    <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
  </joint>

  <!-- ==========================
       Optional optical frame
       ========================== -->
  <link name="camera_link_optical">
    <xacro:inertial_matrix mass="0.001"/>
  </link>

  <!-- ==========================
       Gazebo / Ignition extensions
       ========================== -->

  <gazebo reference="base_link">
    <gravity>0</gravity>
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="pan_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="tilt_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="camera_lens_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="camera_glass_link">
    <sensor name="camera" type="camera">
      <always_on>true</always_on>
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>5</update_rate>

      <!-- Frame id used inside Gazebo messages -->
      <gz_frame_id>camera_link_optical</gz_frame_id>

      <!-- Gazebo Transport topics to bridge with ros_gz_bridge -->
      <topic>/ptz/camera/image_raw</topic>  <!-- topic that image gets published on -->

      <camera name="ptz_camera">
        <camera_info_topic>/ptz/camera/camera_info</camera_info_topic>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>320</width>
          <height>240</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100.0</far>
        </clip>
      </camera>
      <visualize>true</visualize>
    </sensor>
  </gazebo>


  <!-- Ignition Gazebo Plugins -->
  <gazebo>

  <!-- CAMER SENSOR -->
    <plugin
        filename="ignition-gazebo-sensors-system"
        name="ignition::gazebo::systems::Sensors">
        <render_engine>ogre2</render_engine>
    </plugin>

    <!-- Joint position controller plugins for Ignition -->
    <!-- Pan -->
    <!-- <plugin
      filename="ignition-gazebo-joint-position-controller-system"
      name="ignition::gazebo::systems::JointPositionController">
      <joint_name>pan_joint</joint_name>
      <p_gain>20.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>0.5</d_gain>
    </plugin> -->

    <!-- Tilt -->
    <!-- <plugin
      filename="ignition-gazebo-joint-position-controller-system"
      name="ignition::gazebo::systems::JointPositionController">
      <joint_name>tilt_joint</joint_name>
      <p_gain>20.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>0.5</d_gain>
    </plugin> -->

    <!-- Zoom -->
    <!-- <plugin
      filename="ignition-gazebo-joint-position-controller-system"
      name="ignition::gazebo::systems::JointPositionController">
      <joint_name>zoom_joint</joint_name>
      <p_gain>50.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>1.0</d_gain>
    </plugin> -->


    <!-- Velocity controller plugins -->
    <!-- default topic is: /model/my_robot/joint/pan_joint/cmd_vel -->
    <!-- Pan velocity controller -->
    <plugin
      filename="ignition-gazebo-joint-controller-system"
      name="ignition::gazebo::systems::JointController">
      <joint_name>pan_joint</joint_name>
    </plugin>

    <!-- Tilt velocity controller -->
    <plugin
      filename="ignition-gazebo-joint-controller-system"
      name="ignition::gazebo::systems::JointController">
      <joint_name>tilt_joint</joint_name>
    </plugin>

    <!-- Zoom velocity controller -->
    <plugin
      filename="ignition-gazebo-joint-controller-system"
      name="ignition::gazebo::systems::JointController">
      <joint_name>zoom_joint</joint_name>
    </plugin>


    <!-- KEYBOARD CONTROLS -->
    <!-- STOP motion with 'S' key -->
    <plugin
      filename="ignition-gazebo-triggered-publisher-system"
      name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">83</match> <!-- 'S' -->
      </input>
      <output type="ignition.msgs.Double"
          topic="/model/my_robot/joint/pan_joint/cmd_vel">
        data: 0.0
      </output>
    </plugin>
    <plugin
      filename="ignition-gazebo-triggered-publisher-system"
      name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">83</match> <!-- 'S' -->
      </input>
      <output type="ignition.msgs.Double"
          topic="/model/my_robot/joint/tilt_joint/cmd_vel">
        data: 0.0
      </output>
    </plugin>
    <plugin
      filename="ignition-gazebo-triggered-publisher-system"
      name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">83</match> <!-- 'S' -->
      </input>
      <output type="ignition.msgs.Double"
          topic="/model/my_robot/joint/zoom_joint/cmd_vel">
        data: 0.0
      </output>
    </plugin>


    <!-- Pan LEFT  with left arrow -->
    <plugin
      filename="ignition-gazebo-triggered-publisher-system"
      name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">16777234</match>  <!-- 16777234 = left arrow -->
      </input>
      <output type="ignition.msgs.Double"
          topic="/model/my_robot/joint/pan_joint/cmd_vel">
        data: 1.0
      </output>
    </plugin>

    <!-- Pan RIGHT with right arrow -->
    <plugin
      filename="ignition-gazebo-triggered-publisher-system"
      name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">16777236</match>  <!-- 16777236 = right arrow -->
      </input>
      <output type="ignition.msgs.Double"
          topic="/model/my_robot/joint/pan_joint/cmd_vel">
        data: -1.0
      </output>
    </plugin>

    <!-- Tilt UP with up arrow -->
    <plugin
      filename="ignition-gazebo-triggered-publisher-system"
      name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">16777235</match>  <!-- 16777235 = up arrow -->
      </input>
      <output type="ignition.msgs.Double"
          topic="/model/my_robot/joint/tilt_joint/cmd_vel">
        data: -0.5  <!-- look up a bit; negative for your joint if needed -->
      </output>
    </plugin>

    <!-- Tilt DOWN with down arrow -->
    <plugin
      filename="ignition-gazebo-triggered-publisher-system"
      name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">16777237</match>  <!-- 16777237 = down arrow -->
      </input>
      <output type="ignition.msgs.Double"
          topic="/model/my_robot/joint/tilt_joint/cmd_vel">
        data: 0.5
      </output>
    </plugin>

    <!-- Zoom IN with 'z' -->
    <plugin
      filename="ignition-gazebo-triggered-publisher-system"
      name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">90</match>  <!-- 'Z' keycode -->
      </input>
      <output type="ignition.msgs.Double"
          topic="/model/my_robot/joint/zoom_joint/cmd_vel">
        data: 0.20
      </output>
    </plugin>

    <!-- Zoom OUT with 'x' -->
    <plugin
      filename="ignition-gazebo-triggered-publisher-system"
      name="ignition::gazebo::systems::TriggeredPublisher">
      <input type="ignition.msgs.Int32" topic="/keyboard/keypress">
        <match field="data">88</match>  <!-- 'X' keycode -->
      </input>
      <output type="ignition.msgs.Double"
          topic="/model/my_robot/joint/zoom_joint/cmd_vel">
        data: -0.15
      </output>
    </plugin>


  </gazebo>

  <!-- Transmissions for ros2_control (optional: needed if using ros2_control controllers) --> <!-- Example: Simple position interfaces for each joint -->
  <!-- <transmission name="pan_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="pan_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="pan_motor">
        <hardwareInterface> hardware_interface/PositionJointInterface </hardwareInterface>
        <mechanicalReduction>1.0</mechanicalReduction>
    </actuator>
</transmission>

    <transmission name="tilt_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="tilt_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="tilt_motor">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1.0</mechanicalReduction>
    </actuator>
</transmission>
    <transmission name="zoom_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="zoom_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="zoom_motor">
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    <mechanicalReduction>1.0</mechanicalReduction>
    </actuator>
</transmission> -->

</robot>
