<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ptz_camera_robot">

  <xacro:property name="base_radius" value="0.12" />
  <xacro:property name="base_height" value="0.08" />

  <xacro:property name="pan_link_length" value="0.4" />
  <xacro:property name="pan_link_radius" value="0.04" />

  <xacro:property name="tilt_box_x" value="0.15" />
  <xacro:property name="tilt_box_y" value="0.10" />
  <xacro:property name="tilt_box_z" value="0.08" />
  <xacro:property name="lens_length" value="0.14" />
  <xacro:property name="lens_radius" value="0.035" />

  <material name="dark_grey">
    <color rgba="0.2 0.2 0.2 1"/>
  </material>
  <material name="brushed_aluminum">
    <color rgba="0.7 0.7 0.75 1"/>
  </material>
  <material name="lens_black">
    <color rgba="0.05 0.05 0.05 1"/>
  </material>
  <material name="sensor_glass">
    <color rgba="0.0 0.5 0.8 0.6"/>
  </material>

  <xacro:macro name="inertial_matrix" params="mass ixx:=0.01 iyy:=0.01 izz:=0.01">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}" />
      <inertia ixx="${ixx}" ixy="0.0" ixz="0.0"
               iyy="${iyy}" iyz="0.0"
               izz="${izz}" />
    </inertial>
  </xacro:macro>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- ==========================
       Base link (flat disk)
       ========================== -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="2.0"/>
  </link>

  <joint name="pan_joint" type="revolute">
    <parent link="base_link"/>
    <child link="pan_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="300" velocity="0.5"/>
    <dynamics damping="5" friction="1"/>
  </joint>

  <!-- ==========================
       Pan link (vertical cylinder)
       ========================== -->
  <link name="pan_link">
    <visual>
      <origin xyz="0 0 ${pan_link_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${pan_link_length}" radius="${pan_link_radius}"/>
      </geometry>
      <material name="brushed_aluminum"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${pan_link_length/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${pan_link_length}" radius="${pan_link_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="0.5"/>
  </link>

  <joint name="tilt_joint" type="revolute">
    <parent link="pan_link"/>
    <child link="tilt_link"/>
    <origin xyz="0 0 ${pan_link_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.2" upper="0.3" effort="300" velocity="0.5"/>
    <dynamics damping="5" friction="1"/>
  </joint>

  <!-- ==========================
       Tilt link (horizontal rod)
       ========================== -->
  <link name="tilt_link">
    <visual>
      <geometry>
        <box size="${tilt_box_x} ${tilt_box_y} ${tilt_box_z}"/>
      </geometry>
      <material name="brushed_aluminum"/>
    </visual>
    <collision>
      <geometry>
        <box size="${tilt_box_x} ${tilt_box_y} ${tilt_box_z}"/>
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="0.5"/>
  </link>

  <joint name="zoom_joint" type="prismatic">
    <parent link="tilt_link"/>
    <child link="camera_lens_link"/>
    <origin xyz="${tilt_box_x/2 + 0.01} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0.0" upper="0.1" effort="100.0" velocity="0.2"/>
    <dynamics damping="5.0"/>
  </joint>

  <!-- ==========================
       Zoom slider (prismatic)
       ========================== -->
  <link name="camera_lens_link">
    <visual>
      <origin xyz="${-lens_length/2 + 0.01} 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="${lens_length}" radius="${lens_radius}"/>
      </geometry>
      <material name="lens_black"/>
    </visual>
    <collision>
       <origin xyz="${-lens_length/2 + 0.01} 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="${lens_length}" radius="${lens_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="0.2"/>
  </link>

  <joint name="camera_tip_joint" type="fixed">
    <parent link="camera_lens_link"/>
    <child link="camera_glass_link"/>
    <origin xyz="0.01 0 0" rpy="0 0 0"/>
  </joint>

  <!-- ==========================
       Camera body
       ========================== -->
  <link name="camera_glass_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="0.01" radius="${lens_radius - 0.005}"/>
      </geometry>
      <material name="sensor_glass"/>
    </visual>
  </link>

  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_glass_link"/>
    <child link="camera_link_optical"/>
    <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
  </joint>

  <!-- ==========================
       Optional optical frame
       ========================== -->
  <link name="camera_link_optical">
    <xacro:inertial_matrix mass="0.001"/>
  </link>

  <!-- ==========================
       Gazebo / Ignition extensions
       ========================== -->

  <gazebo reference="base_link">
    <gravity>0</gravity>
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="pan_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="tilt_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="camera_lens_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="camera_glass_link">
    <sensor name="ptz_camera_sensor" type="camera">
      <always_on>true</always_on>
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>30</update_rate>

      <!-- Frame id used inside Gazebo messages -->
      <gz_frame_id>camera_link_optical</gz_frame_id>

      <!-- Gazebo Transport topics to bridge with ros_gz_image / ros_gz_bridge -->
      <topic>/ptz/camera/image_raw</topic>

      <camera name="ptz_camera">
        <camera_info_topic>/ptz/camera/camera_info</camera_info_topic>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100.0</far>
        </clip>
      </camera>
      <visualize>true</visualize>
    </sensor>
  </gazebo>


  <!-- Joint position controller plugins for Ignition -->
  <gazebo>
    <plugin
        filename="ignition-gazebo-sensors-system"
        name="ignition::gazebo::systems::Sensors">
        <render_engine>ogre2</render_engine>
    </plugin>

    <plugin
      filename="ignition-gazebo-joint-position-controller-system"
      name="ignition::gazebo::systems::JointPositionController">
      <joint_name>pan_joint</joint_name>
      <!-- <topic>/cmd_pan</topic> -->
      <p_gain>5.0</p_gain>
      <i_gain>1.0</i_gain>
      <d_gain>1.0</d_gain>
      <initial_position>0.0</initial_position>
    </plugin>

    <plugin
      filename="ignition-gazebo-joint-position-controller-system"
      name="ignition::gazebo::systems::JointPositionController">
      <joint_name>tilt_joint</joint_name>
      <!-- <topic>/cmd_tilt</topic> -->
      <p_gain>5.0</p_gain>
      <i_gain>0.0</i_gain>
      <d_gain>0.0</d_gain>
      <initial_position>0.0</initial_position>
    </plugin>

    <plugin
      filename="ignition-gazebo-joint-position-controller-system"
      name="ignition::gazebo::systems::JointPositionController">
      <joint_name>zoom_joint</joint_name>
      <!-- <topic>/cmd_zoom</topic> -->
      <p_gain>10.0</p_gain>  <!-- higher P for prismatic if needed to overcome gravity -->
      <i_gain>0.0</i_gain>
      <d_gain>0.0</d_gain>
      <initial_position>0.0</initial_position>
    </plugin>

  </gazebo>

  <!-- Transmissions for ros2_control (optional: needed if using ros2_control controllers) --> <!-- Example: Simple position interfaces for each joint -->
  <!-- <transmission name="pan_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="pan_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="pan_motor">
        <hardwareInterface> hardware_interface/PositionJointInterface </hardwareInterface>
        <mechanicalReduction>1.0</mechanicalReduction>
    </actuator>
</transmission>

    <transmission name="tilt_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="tilt_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="tilt_motor">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1.0</mechanicalReduction>
    </actuator>
</transmission>
    <transmission name="zoom_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="zoom_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="zoom_motor">
    <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    <mechanicalReduction>1.0</mechanicalReduction>
    </actuator>
</transmission> -->

</robot>
